name: Web Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: 'stable'
          cache: true
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /fluttartur/

      - name: Get dependencies
        run: flutter pub get

      # - name: Static code check   
      #   run: flutter analyze .

      - name: Generate Localization files
        run: flutter gen-l10n

      - name: Build app
        run: flutter build web