name: Web Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: 'stable'
          cache: true
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email mteblesz@gmail.com
          git config --global user.name mteblesz
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/teblesz/fluttartur.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
